# Generated by Django 5.2.16 on 2026-08-21 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('students', '0003_alter_student_tenant'),
        ('subjects', '0003_alter_subject_tenant'),
        ('teachers', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='attendance',
            name='unique_student_subject_attendance',
        ),
        migrations.AddField(
            model_name='attendance',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant that owns this attendance record.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='tenants.tenant'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('tenant', 'student', 'subject', 'attendance_date'), name='unique_tenant_student_subject_attendance'),
        ),
    ]
