# Generated by Django 5.2.16 on 2026-08-21 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_remove_attendance_unique_student_subject_attendance_and_more'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant that owns this attendance record.', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='tenants.tenant'),
        ),
    ]
