# Generated by Django 5.2.16 on 2026-07-25 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        ('subjects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated.')),
                ('employee_id', models.CharField(help_text='Unique employee identifier.', max_length=20, unique=True)),
                ('designation', models.CharField(choices=[('ASSISTANT_PROFESSOR', 'Assistant Professor'), ('ASSOCIATE_PROFESSOR', 'Associate Professor'), ('PROFESSOR', 'Professor'), ('HEAD_OF_DEPARTMENT', 'Head of Department'), ('GUEST_FACULTY', 'Guest Faculty'), ('LAB_INSTRUCTOR', 'Lab Instructor')], help_text='Teacher designation.', max_length=50)),
                ('qualification', models.CharField(help_text='Highest qualification.', max_length=150)),
                ('specialization', models.CharField(blank=True, help_text='Area of specialization.', max_length=150)),
                ('experience_years', models.PositiveSmallIntegerField(default=0, help_text='Total teaching experience in years.')),
                ('joining_date', models.DateField(help_text='Date of joining the institution.')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates whether the teacher is active.')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag.')),
                ('department', models.ForeignKey(help_text='Department assigned to the teacher.', on_delete=django.db.models.deletion.PROTECT, related_name='teachers', to='departments.department')),
                ('subjects', models.ManyToManyField(blank=True, help_text='Subjects taught by the teacher.', related_name='teachers', to='subjects.subject')),
                ('user', models.OneToOneField(help_text='Associated user account.', on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
                'db_table': 'teachers',
                'ordering': ['employee_id'],
            },
        ),
    ]
