# Generated by Django 5.2.16 on 2026-08-21 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0004_alter_department_tenant'),
        ('subjects', '0003_alter_subject_tenant'),
        ('teachers', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant to which the teacher belongs.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teachers', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='employee_id',
            field=models.CharField(help_text='Unique employee identifier within the tenant.', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='teacher',
            constraint=models.UniqueConstraint(fields=('tenant', 'employee_id'), name='unique_employee_id_per_tenant'),
        ),
    ]
