# Generated by Django 5.2.16 on 2026-08-21 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_teacher_tenant_alter_teacher_employee_id_and_more'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant to which the teacher belongs.', on_delete=django.db.models.deletion.PROTECT, related_name='teachers', to='tenants.tenant'),
        ),
    ]
