# Generated by Django 5.2.16 on 2026-07-31 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated.')),
                ('exam_type', models.CharField(choices=[('MID_1', 'Mid-1'), ('MID_2', 'Mid-2'), ('INTERNAL', 'Internal'), ('PRACTICAL', 'Practical'), ('SEMESTER', 'Semester'), ('SUPPLEMENTARY', 'Supplementary')], max_length=20)),
                ('semester', models.CharField(choices=[('SEMESTER_1', 'Semester-I'), ('SEMESTER_2', 'Semester-II')], max_length=20)),
                ('academic_year', models.CharField(max_length=20)),
                ('exam_date', models.DateField()),
                ('maximum_marks', models.PositiveIntegerField()),
                ('passing_marks', models.PositiveIntegerField()),
                ('instructions', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10)),
                ('is_deleted', models.BooleanField(default=False)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='examinations', to='subjects.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='examinations', to='teachers.teacher')),
            ],
            options={
                'verbose_name': 'Examination',
                'verbose_name_plural': 'Examinations',
                'db_table': 'examinations',
                'ordering': ['-exam_date'],
                'constraints': [models.UniqueConstraint(fields=('subject', 'exam_type', 'semester', 'academic_year'), name='unique_subject_exam_semester_year')],
            },
        ),
    ]
