# Generated by Django 5.2.16 on 2026-08-21 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0001_initial'),
        ('subjects', '0003_alter_subject_tenant'),
        ('teachers', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='examination',
            name='unique_subject_exam_semester_year',
        ),
        migrations.AddField(
            model_name='examination',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant that owns this examination.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='examinations', to='tenants.tenant'),
        ),
        migrations.AddConstraint(
            model_name='examination',
            constraint=models.UniqueConstraint(fields=('tenant', 'subject', 'exam_type', 'semester', 'academic_year'), name='unique_tenant_subject_exam_semester_year'),
        ),
    ]
