# Generated by Django 5.2.16 on 2026-08-21 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0002_remove_examination_unique_subject_exam_semester_year_and_more'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examination',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant that owns this examination.', on_delete=django.db.models.deletion.CASCADE, related_name='examinations', to='tenants.tenant'),
        ),
    ]
