# Generated by Django 5.2.16 on 2026-07-24 21:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated.')),
                ('subject_name', models.CharField(max_length=250, verbose_name='Subject Name')),
                ('subject_code', models.CharField(max_length=20, verbose_name='Subject Code')),
                ('semester', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)], verbose_name='Semester')),
                ('credits', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='Credits')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Status')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted Status')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='courses.course', verbose_name='Course')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'db_table': 'subjects',
                'ordering': ['semester', 'subject_name'],
                'constraints': [models.UniqueConstraint(fields=('course', 'subject_name'), name='unique_subject_name_per_course'), models.UniqueConstraint(fields=('course', 'subject_code'), name='unique_subject_code_per_course')],
            },
        ),
    ]
