# Generated by Django 5.2.16 on 2026-08-09 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_tenant'),
        ('subjects', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='tenant',
            field=models.ForeignKey(blank='True', help_text='Tenant that owns this subject.', null='True', on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='tenants.tenant', verbose_name='Tenant'),
            preserve_default='True',
        ),
        migrations.AlterField(
            model_name='subject',
            name='course',
            field=models.ForeignKey(help_text='Course that offers this subject.', on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='courses.course', verbose_name='Course'),
        ),
    ]
