# Generated by Django 5.2.16 on 2026-08-09 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_subject_tenant_alter_subject_course'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant that owns this subject.', on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='tenants.tenant', verbose_name='Tenant'),
        ),
    ]
