# Generated by Django 5.2.16 on 2026-08-09 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('departments', '0004_alter_department_tenant'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant that owns this course.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(help_text='Course code within the department.', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.ForeignKey(help_text='Department that offers this course.', on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='departments.department'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, help_text='Optional course description.'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(help_text='Name of the course.', max_length=150),
        ),
    ]
