# Generated by Django 5.2.16 on 2026-08-09 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_tenant_alter_course_code_and_more'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant that owns this course.', on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='tenants.tenant'),
        ),
    ]
