# Generated by Django 5.2.16 on 2026-08-05 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated.')),
                ('name', models.CharField(help_text='Official name of the educational organization.', max_length=255, unique=True)),
                ('code', models.SlugField(help_text='Unique tenant code used for tenant identification.', unique=True)),
                ('email', models.EmailField(help_text='Official email address of the organization.', max_length=254, unique=True)),
                ('phone_number', models.CharField(help_text='Official contact number of the organization.', max_length=15)),
                ('address', models.TextField(blank=True, help_text='Organization address.')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=20)),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag.')),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'db_table': 'tenants',
                'ordering': ['-created_at'],
            },
        ),
    ]
