# Generated by Django 5.2.16 on 2026-08-09 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant that owns this student.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='tenants.tenant'),
        ),
    ]
