# Generated by Django 5.2.16 on 2026-08-09 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_tenant'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant that owns this student.', on_delete=django.db.models.deletion.PROTECT, related_name='students', to='tenants.tenant'),
        ),
    ]
