# Generated by Django 5.2.16 on 2026-07-16 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated.')),
                ('name', models.CharField(help_text='Unique name of the department.', max_length=100, unique=True)),
                ('code', models.CharField(help_text='Unique short code for the department.', max_length=10, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of the department.')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates whether the department is active.')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'db_table': 'departments',
                'ordering': ['name'],
            },
        ),
    ]
