# Generated by Django 5.2.16 on 2026-08-08 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_department_is_deleted'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant that owns this department.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='departments', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(help_text='Short code for the department within the tenant.', max_length=10),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(help_text='Name of the department within the tenant.', max_length=100),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_department_name_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='unique_department_code_per_tenant'),
        ),
    ]
