# Generated by Django 5.2.16 on 2026-08-08 20:23
import django.db.models.deletion
from django.db import migrations, models
class Migration(migrations.Migration):
    dependencies = [
        ('departments', '0003_department_tenant_alter_department_code_and_more'),
        ('tenants', '0001_initial'),
    ]
    operations = [
        migrations.AlterField(
            model_name='department',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant that owns this department.', on_delete=django.db.models.deletion.PROTECT, related_name='departments', to='tenants.tenant'),
        ),
    ]
